# Site settings
title: Namrata Mukhija
email: namratamukhija@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm looking for full-time research (and applied) jobs in NLP in USA currently.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://namrata96.github.io/" # the base hostname & protocol for your site
production_url: "https://namrata96.github.io/"
github_username: Namrata96
permalink: /blog/:year/:month/:title.html

twitter:
  username: namrata_mukhija

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-redirect-from


theme: jekyll-theme-minimal
