- title: Program Committee and Reviewer 
  organization: NeurIPS 2022 Workshop on Synthetic Data for Empowering ML Research
  years: 2022
  url: https://www.syntheticdata4ml.vanderschaar-lab.com/
  description:
    - The goal of this workshop is to provide a platform for vigorous discussion with researchers in various fields of ML and industry experts in the hope to progress the idea of using synthetic data to empower ML research. The workshop also provides a forum for constructive debates and identifications of strengths and weaknesses with respect to alternative approaches, e.g. federated learning.
- title: AI Ambassador, India
  organization: Women in AI
  years: 2018-Present
  url: http://www.womeninai.co/
  description:
    - Women in AI (WAI) is a nonprofit do-tank working towards gender-inclusive AI that benefits global society. Our mission is to increase female representation and participation in AI. We are a community-driven initiative bringing empowerment, knowledge and active collaboration via education, research, events, and blogging.
- title: Program Director
  organization: Thousand Eyes on Me
  years: 2020-Present
  url: http://www.thousandeyeson.me
  description:
    - Thousand Eyes On Me is a personal branding and talent development platform for women and gender minorities who want to unleash their full potential, gain confidence, and become strong influential leaders. Our mission is to equip female and minority role models to climb the career ladder in all industries, encourage the young generation to go after their dreams, and enable powerful leaders.
- title: Core team member
  organization: Women in Machine Learning and Data Science, New Delhi
  years: 2018-2020
  url: https://www.linkedin.com/company/wimlds-new-delhi/
  description:
    - WiMLDS's mission is to support and promote women practicing, studying or interested in the fields of machine learning and data science. We create opportunities for women to engage in technical and professional conversations in a positive, supportive environment by hosting talks by prominent data scientists, technical workshops, networking events and hack-a-thons.
